#pragma once

#include <string>

extern "C" {
    __declspec(dllimport) unsigned short BeepNow(unsigned char count, unsigned short Int32Beep);
    __declspec(dllimport) unsigned short ComDisconnect();
    __declspec(dllimport) short FindXport(short ip0, short ip1, short ip2, short ip3begin, short ip3end);
    __declspec(dllimport) unsigned short GetAZERTYShiftLock();
    __declspec(dllimport) short GetActConfig();
    __declspec(dllimport) short GetActDev();
    __declspec(dllimport) int GetCardPriority();
    __declspec(dllimport) int GetCardType();
    __declspec(dllimport) short GetDID();
    __declspec(dllimport) short GetDevByLUID(short LUID, short index);
    __declspec(dllimport) short GetDevCnt();
    __declspec(dllimport) short GetDevType();
    __declspec(dllimport) unsigned short GetExtendedPrecisionMath();
    __declspec(dllimport) unsigned int GetFirmwareVersion(short hardware, short module1);
    __declspec(dllimport) short GetLUID();
    __declspec(dllimport) int GetLastLibErr();
    __declspec(dllimport) unsigned short GetMaxConfig();
    __declspec(dllimport) unsigned int GetMyIpAddress();
    __declspec(dllimport) unsigned int GetProduct();
    __declspec(dllimport) short GetQueuedID(short clearUID, short clearHold);
    __declspec(dllimport) int GetQueuedID_index(short index);
    __declspec(dllimport) unsigned int GetSN();
    __declspec(dllimport) unsigned short GetUnsupportedProductErrorCode();
    __declspec(dllimport) bool HaltKBSends(bool bHalt);
    __declspec(dllimport) unsigned short IsCardTypeInList(unsigned short findCT);
    __declspec(dllimport) int Ping();
    __declspec(dllimport) unsigned short ReadCfg();
    __declspec(dllimport) unsigned short ResetFactoryDflts();
    __declspec(dllimport) bool ResetUserDflts();
    __declspec(dllimport) bool SaveUserDflts();
    __declspec(dllimport) unsigned short SetAZERTYShiftLock(short on1);
    __declspec(dllimport) unsigned short SetActConfig(unsigned char n);
    __declspec(dllimport) unsigned short SetActDev(short iNdx);
    __declspec(dllimport) unsigned short SetCardTypePriority(unsigned short cardType, unsigned short priority);
    __declspec(dllimport) unsigned short SetComSrchRange(unsigned short iMin, unsigned short iMax);
    __declspec(dllimport) unsigned short SetConnectProduct(unsigned int bits);
    __declspec(dllimport) unsigned short SetDevTypeSrch(short iSrchType);
    __declspec(dllimport) unsigned short SetExtendedPrecisionMath(short on1);
    __declspec(dllimport) unsigned short SetIpPort(unsigned char i0, unsigned char i1, unsigned char i2, unsigned char i3, unsigned short port);
    __declspec(dllimport) unsigned short SetLUID(short LUID);
    __declspec(dllimport) void SetUnsupportedProductErrorCode(unsigned short v);
    __declspec(dllimport) unsigned short USBDisconnect();
    __declspec(dllimport) unsigned short VirtualComSearchRange(unsigned short iMin, unsigned short iMax);
    __declspec(dllimport) unsigned short WriteCfg();
    __declspec(dllimport) short chkAddArrival_char(short index, char c);
    __declspec(dllimport) short chkDelRemoval_char(short index, char c);
    __declspec(dllimport) unsigned short comConnect();
    __declspec(dllimport) unsigned short comConnectPort(unsigned short iPort);
    __declspec(dllimport) unsigned short getActiveCardData();
    __declspec(dllimport) unsigned short getActiveCardData_byte(short index);
    __declspec(dllimport) short getActiveID(short wBufMaxSz);
    __declspec(dllimport) short getActiveID32(short wBufMaxSz);
    __declspec(dllimport) unsigned char getActiveID_byte(short index);
    __declspec(dllimport) short getBprRlyCtrl_bVolatile();
    __declspec(dllimport) short getBprRlyCtrl_iBeeperState();
    __declspec(dllimport) short getBprRlyCtrl_iPad0();
    __declspec(dllimport) short getBprRlyCtrl_iPad3();
    __declspec(dllimport) short getBprRlyCtrl_iPad4();
    __declspec(dllimport) short getBprRlyCtrl_iPad5();
    __declspec(dllimport) short getBprRlyCtrl_iPad6();
    __declspec(dllimport) short getBprRlyCtrl_iRelayState();
    __declspec(dllimport) short getCfgFlags2_bBeepID();
    __declspec(dllimport) short getCfgFlags2_bDspHex();
    __declspec(dllimport) short getCfgFlags2_bRevBytes();
    __declspec(dllimport) short getCfgFlags2_bRevWiegBits();
    __declspec(dllimport) short getCfgFlags2_bUseInvDataF();
    __declspec(dllimport) short getCfgFlags2_bUseLeadChrs();
    __declspec(dllimport) short getCfgFlags2_bWiegInvData();
    __declspec(dllimport) short getCfgFlags2_iPad7();
    __declspec(dllimport) short getCfgFlags3_bLowerCaseHex();
    __declspec(dllimport) short getCfgFlags3_bNotBootDev();
    __declspec(dllimport) short getCfgFlags3_bPrxProEm();
    __declspec(dllimport) short getCfgFlags3_bSndSFFC();
    __declspec(dllimport) short getCfgFlags3_bSndSFID();
    __declspec(dllimport) short getCfgFlags3_bSndSFON();
    __declspec(dllimport) short getCfgFlags3_bUse64Bit();
    __declspec(dllimport) short getCfgFlags3_bUseNumKP();
    __declspec(dllimport) short getCfgFlags_bFixLenDsp();
    __declspec(dllimport) short getCfgFlags_bFrcBitCntEx();
    __declspec(dllimport) short getCfgFlags_bHaltKBSnd();
    __declspec(dllimport) short getCfgFlags_bNoUseELChar();
    __declspec(dllimport) short getCfgFlags_bSndFac();
    __declspec(dllimport) short getCfgFlags_bSndOnRx();
    __declspec(dllimport) short getCfgFlags_bStripFac();
    __declspec(dllimport) short getCfgFlags_bUseDelFac2Id();
    __declspec(dllimport) char getDevName_char(short index);
    __declspec(dllimport) short getIDBitCnts_iIDBitCnt();
    __declspec(dllimport) short getIDBitCnts_iLeadParityBitCnt();
    __declspec(dllimport) short getIDBitCnts_iPad4();
    __declspec(dllimport) short getIDBitCnts_iPad5();
    __declspec(dllimport) short getIDBitCnts_iPad6();
    __declspec(dllimport) short getIDBitCnts_iPad7();
    __declspec(dllimport) short getIDBitCnts_iTotalBitCnt();
    __declspec(dllimport) short getIDBitCnts_iTrailParityBitCnt();
    __declspec(dllimport) short getIDDispParms2_iCrdGnChr0();
    __declspec(dllimport) short getIDDispParms2_iCrdGnChr1();
    __declspec(dllimport) short getIDDispParms2_iLeadChr0();
    __declspec(dllimport) short getIDDispParms2_iLeadChr1();
    __declspec(dllimport) short getIDDispParms2_iLeadChr2();
    __declspec(dllimport) short getIDDispParms2_iLeadChrCnt();
    __declspec(dllimport) short getIDDispParms2_iPad6();
    __declspec(dllimport) short getIDDispParms2_iPad7();
    __declspec(dllimport) short getIDDispParms3_iPad4();
    __declspec(dllimport) short getIDDispParms3_iPad5();
    __declspec(dllimport) short getIDDispParms3_iPad6();
    __declspec(dllimport) short getIDDispParms3_iPad7();
    __declspec(dllimport) short getIDDispParms3_iTrailChr0();
    __declspec(dllimport) short getIDDispParms3_iTrailChr1();
    __declspec(dllimport) short getIDDispParms3_iTrailChr2();
    __declspec(dllimport) short getIDDispParms3_iTrailChrCnt();
    __declspec(dllimport) short getIDDispParms_iELDelim();
    __declspec(dllimport) short getIDDispParms_iFACDispLen();
    __declspec(dllimport) short getIDDispParms_iFACIDDelim();
    __declspec(dllimport) short getIDDispParms_iIDDispLen();
    __declspec(dllimport) short getIDDispParms_iPad4();
    __declspec(dllimport) short getIDDispParms_iPad5();
    __declspec(dllimport) short getIDDispParms_iPad6();
    __declspec(dllimport) short getIDDispParms_iPad7();
    __declspec(dllimport) short getLEDCtrl_bAppCtrlsLED();
    __declspec(dllimport) short getLEDCtrl_bVolatile();
    __declspec(dllimport) short getLEDCtrl_iGrnLEDState();
    __declspec(dllimport) short getLEDCtrl_iPad3();
    __declspec(dllimport) short getLEDCtrl_iPad4();
    __declspec(dllimport) short getLEDCtrl_iPad5();
    __declspec(dllimport) short getLEDCtrl_iPad6();
    __declspec(dllimport) short getLEDCtrl_iRedLEDState();
    __declspec(dllimport) short getLibraryVersion_Build();
    __declspec(dllimport) short getLibraryVersion_Major();
    __declspec(dllimport) short getLibraryVersion_Minor();
    __declspec(dllimport) char getPartNumberString_char(short index);
    __declspec(dllimport) short getTimeParms_ExFeatures01();
    __declspec(dllimport) short getTimeParms_iBitStrmTO();
    __declspec(dllimport) short getTimeParms_iIDHoldTO();
    __declspec(dllimport) short getTimeParms_iIDLockOutTm();
    __declspec(dllimport) short getTimeParms_iPad6();
    __declspec(dllimport) short getTimeParms_iTPCfgFlg3();
    __declspec(dllimport) short getTimeParms_iUSBKeyPrsTm();
    __declspec(dllimport) short getTimeParms_iUSBKeyRlsTm();
    __declspec(dllimport) char getVidPidVendorName_char(short index);
    __declspec(dllimport) bool pcProxPlusDefaults();
    __declspec(dllimport) unsigned short pcSwipeClearDataAvailable();
    __declspec(dllimport) unsigned short pcSwipeClearOverrun();
    __declspec(dllimport) unsigned short pcSwipeGetBeeper(unsigned short i);
    __declspec(dllimport) unsigned short pcSwipeGetFieldEnable(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldIgnoreLRC(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldKeyCount(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldKeydata(unsigned short field, unsigned short kindex);
    __declspec(dllimport) unsigned short pcSwipeGetFieldLength(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldMagField(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldOffset(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldShowLRC(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldShowSepSen(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldSkip(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldTerm(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetFieldTrack(unsigned short field);
    __declspec(dllimport) unsigned short pcSwipeGetLED(unsigned short i);
    __declspec(dllimport) unsigned int pcSwipeGetSystemCardsRead();
    __declspec(dllimport) int pcSwipeGetSystemInternalCount(int index);
    __declspec(dllimport) unsigned int pcSwipeGetSystemUptime();
    __declspec(dllimport) unsigned char pcSwipeGetTrackData_BYTE(unsigned short track, unsigned short toAscii, unsigned short index);
    __declspec(dllimport) unsigned short pcSwipeGetTrackEnables();
    __declspec(dllimport) unsigned short pcSwipeIsDataAvailable();
    __declspec(dllimport) unsigned short pcSwipeSetActiveID(unsigned short track, unsigned short magField, unsigned short offset, unsigned short term);
    __declspec(dllimport) unsigned short pcSwipeSetBeeper(unsigned short i, unsigned short count, unsigned short Int32Beep);
    __declspec(dllimport) unsigned short pcSwipeSetFieldEnable(unsigned short field, unsigned short enable);
    __declspec(dllimport) unsigned short pcSwipeSetFieldIgnoreLRC(unsigned short field, unsigned short enable);
    __declspec(dllimport) unsigned short pcSwipeSetFieldKeyCount(unsigned short field, unsigned char nKeys);
    __declspec(dllimport) unsigned short pcSwipeSetFieldKeydata(unsigned short field, unsigned short kindex, unsigned short value);
    __declspec(dllimport) unsigned short pcSwipeSetFieldLength(unsigned short field, unsigned short length);
    __declspec(dllimport) unsigned short pcSwipeSetFieldMagField(unsigned short field, unsigned short fieldNo);
    __declspec(dllimport) unsigned short pcSwipeSetFieldOffset(unsigned short field, unsigned short byteOfs);
    __declspec(dllimport) unsigned short pcSwipeSetFieldShowLRC(unsigned short field, unsigned short enable);
    __declspec(dllimport) unsigned short pcSwipeSetFieldShowSepSen(unsigned short field, unsigned short enable);
    __declspec(dllimport) unsigned short pcSwipeSetFieldSkip(unsigned short field, unsigned short enable);
    __declspec(dllimport) unsigned short pcSwipeSetFieldTerm(unsigned short field, unsigned short term);
    __declspec(dllimport) unsigned short pcSwipeSetFieldTrack(unsigned short field, unsigned short trackNo);
    __declspec(dllimport) unsigned short pcSwipeSetLED(unsigned short i, unsigned short v);
    __declspec(dllimport) unsigned short pcSwipeSetTrackEnables(unsigned short trackEnables);
    __declspec(dllimport) unsigned int quickReadSerialPort_char(short index);
    __declspec(dllimport) unsigned short readDevCfgFmFile_char(short index, char c);
    __declspec(dllimport) unsigned int readSerialPort_char(short index);
    __declspec(dllimport) short rf_GetDevType();
    __declspec(dllimport) unsigned short setBprRlyCtrl_bVolatile(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iBeeperState(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iPad0(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iPad3(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iPad4(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iPad5(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iPad6(short value);
    __declspec(dllimport) unsigned short setBprRlyCtrl_iRelayState(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bBeepID(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bDspHex(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bRevBytes(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bRevWiegBits(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bUseInvDataF(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bUseLeadChrs(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_bWiegInvData(short value);
    __declspec(dllimport) unsigned short setCfgFlags2_iPad7(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bLowerCaseHex(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bNotBootDev(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bPrxProEm(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bSndSFFC(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bSndSFID(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bSndSFON(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bUse64Bit(short value);
    __declspec(dllimport) unsigned short setCfgFlags3_bUseNumKP(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bFixLenDsp(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bFrcBitCntEx(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bHaltKBSnd(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bNoUseELChar(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bSndFac(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bSndOnRx(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bStripFac(short value);
    __declspec(dllimport) unsigned short setCfgFlags_bUseDelFac2Id(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iIDBitCnt(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iLeadParityBitCnt(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iPad4(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iPad5(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iPad6(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iPad7(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iTotalBitCnt(short value);
    __declspec(dllimport) unsigned short setIDBitCnts_iTrailParityBitCnt(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iCrdGnChr0(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iCrdGnChr1(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iLeadChr0(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iLeadChr1(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iLeadChr2(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iLeadChrCnt(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iPad6(short value);
    __declspec(dllimport) unsigned short setIDDispParms2_iPad7(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iPad4(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iPad5(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iPad6(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iPad7(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iTrailChr0(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iTrailChr1(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iTrailChr2(short value);
    __declspec(dllimport) unsigned short setIDDispParms3_iTrailChrCnt(short value);
    __declspec(dllimport) unsigned short setIDDispParms_iELDelim(short value);
    __declspec(dllimport) unsigned short setIDDispParms_iFACDispLen(short value);
    __declspec(dllimport) unsigned short setIDDispParms_iFACIDDelim(short value);
    __declspec(dllimport) unsigned short setIDDispParms_iIDDispLen(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_bAppCtrlsLED(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_bVolatile(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iGrnLEDState(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iPad3(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iPad4(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iPad5(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iPad6(short value);
    __declspec(dllimport) unsigned short setLEDCtrl_iRedLEDState(short value);
    __declspec(dllimport) unsigned short setTimeParms_ExFeatures01(short value);
    __declspec(dllimport) unsigned short setTimeParms_iBitStrmTO(short value);
    __declspec(dllimport) unsigned short setTimeParms_iIDHoldTO(short value);
    __declspec(dllimport) unsigned short setTimeParms_iIDLockOutTm(short value);
    __declspec(dllimport) unsigned short setTimeParms_iPad6(short value);
    __declspec(dllimport) unsigned short setTimeParms_iTPCfgFlg3(short value);
    __declspec(dllimport) unsigned short setTimeParms_iUSBKeyPrsTm(short value);
    __declspec(dllimport) unsigned short setTimeParms_iUSBKeyRlsTm(short value);
    __declspec(dllimport) unsigned short usbConnect();
    __declspec(dllimport) unsigned short writeDevCfgToFile_char(short index, char c);
}

// Helper functions for string-based operations
std::string getDeviceName();
std::string getPartNumberString();
unsigned short readDevCfgFmFile(const std::string& fileName);
unsigned short writeDevCfgToFile(const std::string& fileName);
short chkAddArrival(const std::string& deviceName);
short chkDelRemoval(const std::string& deviceName);
